version: '3.9'
services:
  front-service:
    build: ./front
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
      VIDEO_SERVICE_URL: http://video-service:8081
      VOTING_SERVICE_URL: http://voting-service:8082
      RANKING_SERVICE_URL: http://ranking-service:8083
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    depends_on:
      - auth-service
      - voting-service
      - ranking-service
    networks:
      - microservices

  auth-service:
    build: ./auth-service
    environment:
      DB_HOST: anb-web-app-db.c1sugoumkstk.us-east-1.rds.amazonaws.com:5432
      DB_USER: master
      DB_PASSWORD: ANB-WebApp1234!
      DB_NAME: anb-web-app-db
      DB_PORT: 5432
      SERVER_PORT: 8080
      JWT_SECRET: clavesecreta
    ports:
      - "8080:8080"
    networks:
      - microservices

  ranking-service:
    build: ./ranking-service
    environment:
      DB_HOST: anb-web-app-db.c1sugoumkstk.us-east-1.rds.amazonaws.com:5432
      DB_USER: master
      DB_PASSWORD: ANB-WebApp1234!
      DB_NAME: anb-web-app-db
      DB_PORT: 5432
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - microservices

  voting-service:
    build: ./voting-service
    environment:
      DB_HOST: anb-web-app-db.c1sugoumkstk.us-east-1.rds.amazonaws.com:5432
      DB_USER: master
      DB_PASSWORD: ANB-WebApp1234!
      DB_NAME: anb-web-app-db
      DB_PORT: 5432
      SERVER_PORT: 8082
      JWT_SECRET: clavesecreta
    ports:
      - "8082:8082"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge