name: CI Pipeline

on:
  push:
    branches: ["main", "dev", "feature/carlos"]
  pull_request:
    branches: ["main", "dev"]

jobs:
# -------------JOB 1: Unit Tests --------------------------
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/auth-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'

      - name: Instalación de dependencias
        run: go mod tidy
      
      - name: Ejecución de pruebas unitarias
        run: go test ./... -v -cover -short

# -----------JOB 2: Integration test-----------------------
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    defaults:
      run:  
        working-directory: services/auth-service

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpsw
          POSTGRES_DB: anb_test
        options: >-
          --health-cmd "pg_isready -U testuser -d and_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'
      
      - name: Instalar dependencias
        run: go mod tidy

      - name: Ejecutar pruebas de integración
        env:
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USER: testuser
          DB_PASSWORD: testpsw
          DB_NAME: anb_test
          SERVER_PORT: 8080
          JWT_SECRET: Secret_for_tests

        run: go test ./test/integration... -v -cover -tags=integration
        
